---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age10vugm6mf3fsxxsjwywsldd58gqam9grysxdh5g9y7ygnj72wlsmsv34ra2"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age10vugm6mf3fsxxsjwywsldd58gqam9grysxdh5g9y7ygnj72wlsmsv34ra2"
