apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:lvcuYg8+1UT63DeuQc/7KVkup1kWUjGMlUUAdKPQWM0PLMs/,iv:X6O9+gyM7NrIuuwaVNXinxlyhSzwbKbt2O13SOsVoV4=,tag:mYqM1BwliaplVYTU0yLBuA==,type:str]
    credentials.json: ENC[AES256_GCM,data:1siPvGkpc7YwSM1o6iLEsP0xCfRs/J7u/SR2rvZNSL7nmxAZK95aIioFQQEStrcDWyAWTdd0eOceAH3ASwpDioH70Y1DHmM+MpfTfE5FCOjD/mbTgOK4Osh7324arPRliycB8PmmP1IF6UX7+A0h00Qewz97KfWTk3OySh23xQ3Dvt4Dn2GehExoun5qvPnBqNmA7sEi3qm+1+OXs8YstzedTvaiOPp1YNzRm+DhJg==,iv:Xya/B6jOUQ95WqT/0ADRLKv3JM2x0XZ2W/ULdnwG6NM=,tag:wJxvE2IzuglP7PxjfT1YZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7crj2phf2gt4z0smc3jsetczj89g7j9w2g4d43psgz2q4dqe4tqr3v7c7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cHE1N0VvZjBJcWFucDlm
            TW5ueUpzQ3pUMnd1VUViR1hOSjgxR1A2eHpnCnVFTStNMmZPWjk2SGZ4NnhDZzFE
            ZEwycm1Ha0FYTldxbFlmalhMbVZTaXMKLS0tIDNQSUdpbkZIUUxxYmNLMEJtc2RC
            N0pqSk5XdWJ3dndFNG9JN0V6MklGQWcK3/GZ2J09liW6P8pbqKSP7L0iasNBrSQH
            F0Dxp24+UEfgFXHCaZW2v7DuW5qcOsCd42A9djiO1LEU/r/EDiXxWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T17:48:06Z"
    mac: ENC[AES256_GCM,data:WWvu9ngWcLzpLsN9nYkhH77OBT2IDpHQOY+k2fkKQEJ4OstVAOZJzIQbxSEXf4iVTRenVzsSXK8bHDCRBrantVup2AVwBuddccOoDDEFnjIM8RW31e/Ts2i4gqXLcQIBb4HLXWFX29ncRqDkjWYngedM0KHVGXeIyMkWk2rSo9c=,iv:697LUZq9CtaybOjoUvZKUVKPXt/AQpYIKM6Qd9NGebM=,tag:tsGE+7DUN1/pszPDRmWpIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
