apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:2Zi46zO9AlG0cDuJOLtPZ4iHg2tUqyKwCaEWYEoXlg5mdMb7,iv:IihXNsMpzL0jbduKTLRtbrDTd7QBg7RNfOhFVBD1f8w=,tag:IJKigu7k1yKnLcSYC18bLA==,type:str]
    credentials.json: ENC[AES256_GCM,data:WdcJ2z5nJUzD1ivstxLUgi0Mpr2yd+mVp1qhR4aOxMhWW7eb6IFWeas9QYJFZ80ERrPTDtgl3t9iugyri+Okatpv/puMT0ZJNACFZFb5LElMPqjXvtTGcMwOB1XqIca8QcFkKmlREQZHFSGWNz1Jtov+SaMHARzCurC0TnDgrOaZSGrF5vPe97vDPUsoPMX+JzqW4lx+okFzclBBxQHk9oKnCsEQLsERx0URMyv8DA==,iv:kOTAmrKd7AhNLiVQSblGKSasdDTIS83kczvKqgxtXm8=,tag:qrJW2aTZbjCQBpBgarxDeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7crj2phf2gt4z0smc3jsetczj89g7j9w2g4d43psgz2q4dqe4tqr3v7c7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbzUxRHk1bDJRb2U2Vmk4
            dUZyTUYzcjJCbUV2VENrWUM5bUI0K3lRR0J3CnFtMWhMKzNzU0x1TTY0TnNRRzFO
            NlMrUXBEdVVOR0t5SUNTci93Y2hNOTQKLS0tIFcvU0R6Mk1IbU1pWkVKSklZUWRu
            MktJQWxMVWFUYVpNZDdlL1U0d01jZkEKIw3Su8EO23lPRTHbf5md3P82RuuJPelL
            VCEOF3mCp00aben9VmT4tkkk8lJiyp63nC1N7htewY5WmY3JGWMBLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T13:06:57Z"
    mac: ENC[AES256_GCM,data:Mxn6E6AprVyqKDOiAyP6LkPNeTc+CncdkjBqwAWeuB7ZrWBE0kXqPK+3eguzrs8qz/hZn9cBuHIN86OkPY+bdcvLC3/rjDqRCNKpSyTL06Qlfl/PlbUo+UTvyzAl3reasJgvh9awP7mp94vsvVcRlax2jBh1Jf4w/H15ViXfnVM=,iv:HJR5VknkF2Yqx9SlVBZcTNS1MICuNzcvchlb+ZNwalU=,tag:yW0wcp9ZkpSfHfakVQQkWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
