apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:E/CGdex47GHh2lJ19CNj3lwDvMCbS7WWnrbzEgQRKPiWaX7/audUog==,iv:7QiUsZ3NNUPrbEb8J/R+2Gq6bHfQtJhF0aze1dVAAJk=,tag:DHNUAfEuD7Z17uLzSnwWDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7crj2phf2gt4z0smc3jsetczj89g7j9w2g4d43psgz2q4dqe4tqr3v7c7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArblorUkR2RHE2VTZQd2w2
            R0pBdlVJQXVsUHY0QTNTU2E1c1F0RlY4UndBCnp4QXM5S0ZxMHdlMW9qY0tYTGxP
            UTVvWmtXc0Vqb3B5TUtzYUlOdld1Qk0KLS0tIFpvTnhMcG92WGFpZmZBendzenZD
            QVJpbWlqZWZ1Z0Z2ZGE3ZHRyTkhCTHMKb0eAI/5osh4UCrx5DUDmlsG9KZC5lJwW
            UvXphcEfhxuN7bWZU68clBP9Ym21zqKQ9Khh82ai42S900cwtSnzrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T13:06:57Z"
    mac: ENC[AES256_GCM,data:dCGV54nnInvranO8jU/0GqcxIXCcycG2kzOC2/NQQgn7z7G4BswAix1FO/djPMWKGpNib9YppE8/8hE5rfXiIC2BmmQTtq48ZV4i1QPubggWNr61YE8HmuTg4ILILVdqbRsK+463DP3hc+cCJpdNgCWIBmDNa/hDhSbv/1plOd4=,iv:zG1NalBy0oFzjDWuxbnJhzUBQldh61v7U4MXjtqU0k8=,tag:JtR0H/B2CLoX66JGo9y5mA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
