apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:BhjUt0SHpRa9O9eN3LmHe35LrGS4Jws1BLoWT6SIz+lciwa2ISy0PA==,iv:ApvCNkiSWbX8Uyy8sTudqzVL4ftfPUvOGYyKJSLw58M=,tag:PkRk4vhjir7NzjK2GX5PVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10vugm6mf3fsxxsjwywsldd58gqam9grysxdh5g9y7ygnj72wlsmsv34ra2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhT2RBbWFZaXNnUUlJZCti
            VWtUUXNmNzlYS0grT0JLbHViRWsxNjVDckFFCmpPcjk5SHdHMmVjT0FLQWpwMTZK
            ZnorMnhoSjlEUHdHWTZwQ0lnMjFTdjQKLS0tIEg5TWtOQU9lK0IrbERoc1pnLzY0
            VVVZWTRXejFHRzkva2RpZXNpVHFURFEKmdSoqtGoSHVF3fxh8poNBzjLPuXuZP9j
            HKX/dOnnDhw3tCsM8U3e3b4ZEAXixBGoja/64sp2sWtJ4RkImNstQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T16:55:01Z"
    mac: ENC[AES256_GCM,data:qUW2zIKJkEGivVM/mBCVq6oIS4C3IyA5qmOUI2r6sXOJCZLH+Q6TBRc2wpmJLjx7DHgsD49wo/C34cn7nJQgB4WjF4FSBoWedyO1zwpCzl5K65p8/e2qAPXpDbM/ivmncVgESkRXhVbPb+WNF/5wIwtFfRmcpCKF8YQmHx3MK6k=,iv:FcfHdiO0ydkSDV4Uqu90fghSib+/O3jStpv88ocQmJ0=,tag:YbD00dzM9VIEktVNG7t1jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
