apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:xjY6s/j2g9e2dzOMnmVC1WPKc6X5QAl7XgO4VkA/2eClkg70gnXLrA==,iv:FeZFSL151aBlPIWbwUkOKyMRlSqQKWeRImf/ED6E8Bk=,tag:XRG95q1MNlduxBJRLJkrbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7crj2phf2gt4z0smc3jsetczj89g7j9w2g4d43psgz2q4dqe4tqr3v7c7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMDdHTnI4R2x5enFGL0ZC
            ak5ScFU5QU9aMWdxdnd4S3BtMFI1RjNLTFEwCk56ajgxVklQVGhZZktjRUlmTUNk
            M2lkOW0vYmM4dXI1cVNXNkRCZ1dRM3MKLS0tIElwVE1QNFJvVHJoQzZoZDNKcFhi
            a3M3RjdveThXOU9jNDJiUlBrS1RuQUEKQVMkfMMSbpkRZf80oPULSWY2EbKLwgqP
            m6XXSVci2svExYm8F4XHidrokWsiCGwZ2ARyQZt+0A/16KZHnfTWpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T17:48:06Z"
    mac: ENC[AES256_GCM,data:PrKiRqC9uW2f3H0ZYp+k4Os0TKVpYsYUCFr1Gc60xaBzH6O73QFALnFYVwBqP0ygvsGWxWUMNdqG1/b3FWcaSwGlSl8rlXCcuw7GPvCFscHw5nqRssfJ8fm074++o5i22doAE3vb1hjyprVSRe2SJYAdwtMBbMz+JaB/ubuQM0Q=,iv:yBkrQPss1VukOnVmGkzm5FfkTMV6WuElsV1xKQyQG2o=,tag:99nm8j2AB5mz5nQiwm/vkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
