apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:1FPd7Jts22tPehSrp33BLw==,iv:Lc6dNNNDcPcgf7419liHy9b1NLnDiOH+l2PTvkZWk/w=,tag:bebZUlK+OCgoj+4OCw+Vvg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:WvxUgPG1kMoQJlX9N/hgXfM=,iv:d4X+qPTdxrKDKryF9h3CvIZynyzsp/LQg4eTzMNsllY=,tag:71x9yMTv32caxjhU16L1UA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:FNox+uk7iULf9jFkIOgEEuQW6gw8dKwiifcEMxeOOBBv026+,iv:SdUqh3QpFg1kAIpDBvVIoos8Jp7qlhOTH6fqgzG3sSY=,tag:3whm9bH5oEVIZNc9JEJcfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7crj2phf2gt4z0smc3jsetczj89g7j9w2g4d43psgz2q4dqe4tqr3v7c7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcDh3NEFzVU8yMVdJWXFa
            S3Iybm1mY0NWOWRxcTZwam44UHRKQ1JwdXdJCjl4RHZoRXJZNExJZHhlSVBoa0Jq
            bHdacjErTXVnNngvb3lvRHA2YUZMSDQKLS0tIEozRlVsTkZtSWxqNXpFaWNOM0Zo
            L1I5VW1yRXNYWFJLOWxTTUE1bWQ4emsKcgmlkNJ/RUd/h9ClE/vIeYDGDyR9k548
            lL97w0gg1EwxUQQpRAl2Mss7KUEyYmNy7vDNLD/HYyc8X5FicijlQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T13:06:57Z"
    mac: ENC[AES256_GCM,data:lx1YdgxXU1b3crm9Rh+HxqCjFa7yQikYJetimbW3zboruYG3xaeQ62w35XjzBzdS3UBVgwnyVVtWUeWMRg6ZLNd6kam943G88WduMR/JqwxFfo0gALvNlgHo6Z/NH5/omzhVNM968Wv/oe+9vFBE0BPi+M2T286t5hJeIHJ/0BU=,iv:y3FdsApNlj4OlnupeplvNwc5nidDmc7h8NjxKJ81le8=,tag:UrOWDfnsvvlmk3MUHbwf4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
