apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:izY9rQj1Y9g84542/8lRiw==,iv:fCgyKzQmBuO0UlQFQSfW1u8Q23/5M6WqWd1WOOHBf90=,tag:Me3tk6PYEcIOHoU1pBWSRA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:RnG0PGGztLxAV3YPhaDs+Rc=,iv:XJ+9CX1e21ILbQxOY7a/QCPgqrCOCGkl65Y3h7G5BuA=,tag:9KSsHeTBrczOVIjpdsTcUQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:nhMer7KBU/rZiUHBDVxgblArqWl92x8FntIhiltXqs1kRv3P,iv:eOO6ABtG2Hek+H7z2BgDkmIjBAoiM/rZcsfqjGo6MHM=,tag:1y4BPaNnjO7N2q01ATzg1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7crj2phf2gt4z0smc3jsetczj89g7j9w2g4d43psgz2q4dqe4tqr3v7c7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUC9UZUtqSUN5KzhGaHdJ
            TXRDajdTZW5jTENXL1ZHMUZ2dVNyUmE1c1RzCjJHTzQ5eDNaU21Dak9OcTQzVzlL
            VHpkRnV1d0Yvc2p2dUVUN2VvcFQ4ZW8KLS0tIFdGOG16ditGbWZ0MmF0OXEwUW5D
            bjg2V3NnNFI0bVo2d08vbGZsWXc2UTQKr1N63ZMYI0CC4j1m920DrK7aeGTGzW3w
            CAcdcWX8bsHXpYkrHfs+lG0dmvGCqa+wrztA4FDhClcoq6gZ85b86Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T17:48:06Z"
    mac: ENC[AES256_GCM,data:9eBIUoi4H8l9buaaCB8b9XNGXWB1bnyyUGJ5zZZ4+OzcJedJQyvyBiU5SAOOnkw26SlXRj+mCwD36VjpX5iQm2DQ+lD6ZCbfOSn85Xqcq51osiz5ZOcpXNTHmvhxDEJFF1OjuMyVEF2KlFxmyqb2n5xM3pCJnr6/QlomF4BxhRg=,iv:qcewltpAd9+y9dDk8zrv9zY7g0wVdzqRqOiZSkYS+l0=,tag:v0zdYqhtxFBsiSJt2LiP8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
