apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:V7gLlEIW0TX1keL2LnRPwAI/yx9V9Z1cHopBkNlvQi0=,iv:FHgorcZJGZolJaf44+GkQvAVb2Mr38PR8b9uRroCGWM=,tag:P8FwTnXncoGL1H+qWpMpog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7crj2phf2gt4z0smc3jsetczj89g7j9w2g4d43psgz2q4dqe4tqr3v7c7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdFpza1FKZmliZzNwUUg5
            dnFCN05qUkl0RE5Jc2dpN2ZnR1ZjOVFSNUVrCitMZ01sL1VrMUdwMzhvOS9VWFN1
            UHlxc2VtVlhXTlh0eG1Kcll1ZVdsTHcKLS0tIEZuNURVam5UQUc1Z1RDWnkyc1dD
            alFUWGsvRlJvRU9XNy9ucTVEaHdHWEUKFMl+ouc2D8vzNIzN2gZllEcg2HKTXLry
            ubjb6z0sg8p4kZPjseGCMU8bw4GNUhbQwB0bhsgHibaPkGiWh+YNwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T13:06:57Z"
    mac: ENC[AES256_GCM,data:ECQyImRh9ClqrWRsisSyKzf2r5dMYh349Vy/ZKAdMQ4yOCCtYFNGBSS1a2m40ujkerd97qGE472m6G8ZmMvg1neb6W93cI4yl+lKlaaXJDRvyeHZERkxdL0OIKL3778hFny54nm1ZmoYC1KnVN8E777G2HoMIw1YzK5ku8nR3ns=,iv:KV0zym2gnhXl1xC0vkMqScnDcHK+XiEcgVohfDSZSNE=,tag:9z7z0+THf1w9+LqPtlGong==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
