apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:pJRc1zVfqIO/NPc3e4ZvL7mz8+5JZYHie7OnILGlWRo=,iv:OidxjoE22j8xDrHPzm+BWbwM1Upn8Wdq7p1yGIKOehQ=,tag:HRJPgzoGIAfXWBbBfS8nGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7crj2phf2gt4z0smc3jsetczj89g7j9w2g4d43psgz2q4dqe4tqr3v7c7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNenQ3cGIrQzk5V01aQXhN
            SnZTeitBa2cyeDhIUjBYUVVRUzRqd0Q2WjN3CndJM00vRzQyMkg4SGRsMnlTS1dK
            dzhJWDRmQ2p1Rm01TU5RemRwSERHMlkKLS0tIFlPUGYwbmdIUHk1cktVYU95bEJD
            WGloaDczMXlTdEFJeEowdGdGT0lHR1kKtUCNlEgZeVniGl45zz/IKSSpYyTIkLdp
            aCXURcKzIc1zbyCSxxe+shynhSt+9jyM8AdfRF1dzi1jGfy4y5ir8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T17:48:06Z"
    mac: ENC[AES256_GCM,data:iqJ8yi3tnlCR/VWPNiiOiql2Zh78AHF62pRqTYOLOKuthAv3uhIYXjbT3KPZRXsT5mGknYUPOGSqXS06nyxPnRtz1EE3FD1FSo4Y1Klb0ScL0fvh7ZmqJB7IUDvCbguIQfPF5zvwsB9pJczeuAXeQAJK8CnhTKPgNjADdfahzno=,iv:N0JppIg1X+zvwPP5u64XFje0V7TXvR2tnu8+Hnfcako=,tag:LT0hQqYqenzDBZUKYHC9OA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
