apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:oKEW/W/Dwcgant01lM3jv7xJN1kJIX0NKrGQR1UV6hfjG1yOIV8Nng==,iv:v07AdWYWPukXUHdQX8Yd4o5a62H+ei+Ib+ZhE1Be+4Y=,tag:IlcRUWWLv03qMOMsSBD75Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10vugm6mf3fsxxsjwywsldd58gqam9grysxdh5g9y7ygnj72wlsmsv34ra2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMmwrRUM4ZWM4bGtlV0pS
            dmVGa2d6emVXUTI5cWNQakExSlliVTdYL0QwCk1HdHUwNlNUQjJOWlRqcDdjY0Nr
            UXRyTWlGdGZ6S2VWendSV0Z5dUdTSU0KLS0tIEtPUmMvUnNlSFUzSGdqVm5ydWls
            RlpVeDJLelRoQk9VQ2RyQUdOelo0L1EKubvfcAHQ4snMTznYGuS0RR0GSNNd6sqj
            rUBgerlj4IIQkCYNsShRdnsZ46gLRs10dMpXcW31BGUj3zBpPlo0uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T16:55:01Z"
    mac: ENC[AES256_GCM,data:xKBZOdchiKE4rXoCo23kB7yyWK0TmADEpzprnhHzV/plmFYGmVcTZNSEGZkQD+WMydMDwicDx20E0yUF4wcZ6evIeZUfHFOGhz+h4x1jjn6kPvDwTNli0D5reLeZtYgTkY5aZ27Dbo/za0Xtzy+sf3a3Sio+rz5D8ERwRqZ43CA=,iv:4pjUEk0ETUMyyUth0LEBgTYaCe/3kBprB9Ad31M6ma4=,tag:2lQjNn0wUx9SQNJ1dZAnQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
