apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ywtd38DZiw3unObLjfhjc0SInPMN84ym/pJbd02EbsCjqv6b9C5J6A==,iv:dLBkqslsPVad4+98si6rerl3VpVBPTYY69sbIPJXGzA=,tag:gOsjOK+COBNcQZIdI9VAcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7crj2phf2gt4z0smc3jsetczj89g7j9w2g4d43psgz2q4dqe4tqr3v7c7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bjhqNHZ4NE9tSXFaOUZY
            VnZTV2tTdmp1RHBOTVN1ZVVQeGVSZCtDUUJRClErNEdPdnBnRXNlTjZCTDZQN1NM
            REF1SllZU1cvbzJ3bUdQTkhZQ1E1TFUKLS0tIHQ2YVlOZjk5Kzdqa1k4RnhMRlNk
            Q3NIS25iaC9SNUpqSTJKR1pVMFlsUWcK/m+Rzk3UqlIT+Pq9ZP5IXatfuYPEbmq1
            vgqx+gVWhwrgTB8s4zzlwT2rr1JSj5fJFCULVBTH52D9Kecfd8nXQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T13:06:57Z"
    mac: ENC[AES256_GCM,data:hlS3/0HJ86aRmrNZwIM81+IRxCyRm6H2Sm5M3WooG5DDxapZCsY9f3wB2vsZm6b6VPu9WEErYiuuAiwxZwUYb44S5/dTgP9xA/0A9bX8BmXzPydIulFJ3ZG3ekbHmbSx9HEBJEeCp/n5SWvg7wQyLXPgoPmurGre1kIySl1f7Ak=,iv:+YwTfHuFipw5WehhPmG4ffca7W9+8xBS9Tq0PFZGtAk=,tag:O69UM863GzJrfbDkWY9w5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
