apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:swrbf3wZ2N3Uae42jMMvvYBTFZk2HE1tqd6KVytyR0eqv//ogdg+wQ==,iv:SrN2G15bVR+uXF2y07U0xY3uklCpRIF1UljQA3pu3GA=,tag:XWumEThApBJSahWSJDq30A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7crj2phf2gt4z0smc3jsetczj89g7j9w2g4d43psgz2q4dqe4tqr3v7c7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4R2FwN1dYVnF3NEhZekNz
            YU4zVDREellTTWRwZThidElCaFFSYko4eFJ3CkMzZTNwdlR1Tm5JbmJVWG1sYThN
            cVkwTUdXOWpnZjY1bS9ieHhxcmorS0EKLS0tIHRnYUplc0luVk0yWTM2YnVoR1BQ
            Q01pOUxzemdhQlBNTERtVE5lVnRxcU0KKh9DlsKYT5kRW+tXGTtxkkj1ncp3xq8S
            Dv5UTf8l5OKCuvikgj1UAYAlg+vdUC2nl861EuKtaIEhhFE2cnvrpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T17:48:06Z"
    mac: ENC[AES256_GCM,data:AclIlH3SJi3y9824biS2W5DsWSO3Ts+1s/TEXwhmMt4O3sRNEXYZQkbHOfUIaRMV4YidlDBoIBO1rUC2/Zk0Kg1teN3AqE1rxsQ1qAizK3m/b67nZWzjrCZO4LUTfEiSdycN3gH3hbQvC0h6Uvuf/4oNoz3tWbtIinKxemhzWpQ=,iv:sQXeTORLcawK4rOWTmPsxhV8D2cJfSxpauAc0Ks7dtk=,tag:N7G+R/U+qVpENtol1mShag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
